/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadarRiscoRouteImport } from './routes/radar-risco'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObrasIdRouteImport } from './routes/obras.$id'

const RadarRiscoRoute = RadarRiscoRouteImport.update({
  id: '/radar-risco',
  path: '/radar-risco',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasIdRoute = ObrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/compras': typeof ComprasRoute
  '/obras': typeof ObrasRouteWithChildren
  '/radar-risco': typeof RadarRiscoRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/compras': typeof ComprasRoute
  '/obras': typeof ObrasRouteWithChildren
  '/radar-risco': typeof RadarRiscoRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/compras': typeof ComprasRoute
  '/obras': typeof ObrasRouteWithChildren
  '/radar-risco': typeof RadarRiscoRoute
  '/obras/$id': typeof ObrasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/compras'
    | '/obras'
    | '/radar-risco'
    | '/obras/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adm' | '/compras' | '/obras' | '/radar-risco' | '/obras/$id'
  id:
    | '__root__'
    | '/'
    | '/adm'
    | '/compras'
    | '/obras'
    | '/radar-risco'
    | '/obras/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmRoute: typeof AdmRoute
  ComprasRoute: typeof ComprasRoute
  ObrasRoute: typeof ObrasRouteWithChildren
  RadarRiscoRoute: typeof RadarRiscoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radar-risco': {
      id: '/radar-risco'
      path: '/radar-risco'
      fullPath: '/radar-risco'
      preLoaderRoute: typeof RadarRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras/$id': {
      id: '/obras/$id'
      path: '/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof ObrasIdRouteImport
      parentRoute: typeof ObrasRoute
    }
  }
}

interface ObrasRouteChildren {
  ObrasIdRoute: typeof ObrasIdRoute
}

const ObrasRouteChildren: ObrasRouteChildren = {
  ObrasIdRoute: ObrasIdRoute,
}

const ObrasRouteWithChildren = ObrasRoute._addFileChildren(ObrasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmRoute: AdmRoute,
  ComprasRoute: ComprasRoute,
  ObrasRoute: ObrasRouteWithChildren,
  RadarRiscoRoute: RadarRiscoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
